//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocaoTemporal
    {
        public int pId { get; set; }
        public System.TimeSpan tempoExtra { get; set; }
    
        public virtual Promocao Promocao { get; set; }
    }
}
