//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.EF___Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AluguerView
    {
        public string serial { get; set; }
        public int eqId { get; set; }
        public int empregado { get; set; }
        public int cliente { get; set; }
        public System.DateTime data_inicio { get; set; }
    }
}
