//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.EF___Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocao
    {
        public Promocao()
        {
            this.Tipo = new HashSet<Tipo>();
        }
    
        public int pId { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime fim { get; set; }
        public string descr { get; set; }
    
        public virtual PromocaoDesconto PromocaoDesconto { get; set; }
        public virtual PromocaoTemporal PromocaoTemporal { get; set; }
        public virtual ICollection<Tipo> Tipo { get; set; }
    }
}
