//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.EF___Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.Equipamento = new HashSet<Equipamento>();
            this.Preco = new HashSet<Preco>();
            this.Promocao = new HashSet<Promocao>();
        }
    
        public string nome { get; set; }
        public string descr { get; set; }
    
        public virtual ICollection<Equipamento> Equipamento { get; set; }
        public virtual ICollection<Preco> Preco { get; set; }
        public virtual ICollection<Promocao> Promocao { get; set; }
    }
}
